version: '3'
services:
    application:
        container_name: application
        restart: unless-stopped
        volumes:
            - ./data_host:/app
        ports:
            - '5000:5000'
        network_mode: host